swagger: "2.0"
info:
  title: helloworld/v1/helloworld.proto
  version: version not set
tags:
  - name: GreeterService
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/helloworld/{name}:
    get:
      summary: SayHello sends a greeting message to the user.
      description: |-
        This method expects a GET request with the user's name as a path parameter.
        The server will respond with a greeting message.

        Request:
          - `name`: The name of the person to greet. This should be passed as a path parameter.

        Response:
          - `message`: A greeting message that includes the user's name.

        Possible HTTP responses:
          - 200: The request was successful, and a greeting message is returned.
          - 400: The request was malformed, usually because the 'name' parameter is missing.
          - 401: Unauthorized request, typically due to missing or invalid authentication credentials.
          - 500: Internal server error, indicating a problem on the server side.

        Example:
          GET /v1/helloworld/John

        Response:
          {
            "message": "Hello, John!"
          }
      operationId: GreeterService_SayHello
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GreeterServiceSayHelloResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: name
          description: The name of the person to greet. This should be passed as a path parameter.
          in: path
          required: true
          type: string
      tags:
        - GreeterService
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1GreeterServiceSayHelloResponse:
    type: object
    properties:
      message:
        type: string
        description: The greeting message to be returned to the user.
    description: |-
      GreeterServiceSayHelloResponse represents the output from the SayHello method.

      Fields:
        - `message`: A greeting message that includes the user's name.
